from setuptools import setup, find_packages

setup(
    name = 'pywapor',
    version = '3.6.0',
    url = 'https://www.fao.org/aquastat/py-wapor/',
    author = "FAO",
    author_email = "bert.coerver@fao.org",
    license = "Apache",
    packages = find_packages(include = ['pywapor', 'pywapor.*']),
    include_package_data=True,
    python_requires='>=3.10',
    install_requires = [
        # 'libgdal-netcdf',
        # 'libgdal-jp2openjpeg',
        'netcdf4==1.7.*',
        'gdal>=3,<4.0',
        'xarray==2025.3.*',
        'numpy==1.26.*',
        'pandas==2.2.*',
        'requests==2.32.*',
        'matplotlib',
        'pyproj==3.7.*',
        'scipy==1.15.*',
        'pycurl',
        'joblib==1.4.*',
        'bs4',
        'rasterio==1.4.*',
        'bottleneck',
        'tqdm',
        'dask==2025.4.*',
        'rioxarray>=0.19.*',
        'cryptography',
        'cachetools',
        'cdsapi==0.7.*',
        'shapely==2.1.*',
        'lxml==5.4.*',
        'scikit-learn==1.6.*',
        'numba==0.61.*',
        'xmltodict',
        'google-cloud-secret-manager>=2.24.0',
    ],
    classifiers=[
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ],
)